### ISSUE TITLE
Error starting UltimateTS

### ISSUE THREAD

**Issue by Harveh** [DiscowZombie/UltimateTs#1]
I'm not sure what the issue could be. The plugin is disabled in-game, meaning it's red when you do /plugins. If you could help me, that would be awesome!
[https://pastebin.com/zShNqu4T](url)

**Comment by DiscowZombie** [comment]
Hi, 

I think you do not have enter your true connexion informations. Have you entry the correct combination username/password ? 

Do you use a TeamSpeak server hosted on default port 9987 ?

**Comment by Harveh** [comment]
The server port is 10097.

What do you mean username/password. Are you talking about the server query?

**Comment by DiscowZombie** [comment]
Okay! Your TeamSpeak server isn't hosted on your purport machine!

You need to modify "virtual ServerId:". Ask your hoster to get your virtual ServerId.

**Comment by DiscowZombie** [comment]
Hi,

UltimateTs v2.0.0 is here, I think your problem were fixed in this version, can you try ?

**Comment by Harveh** [comment]
Nope. I have my virtual server id now.
https://pastebin.com/c7bGsSpk

**Comment by Harveh** [comment]
Here's my config.
[https://prnt.sc/fa6u53](url)

**Comment by DiscowZombie** [comment]
Hi,

unfortunalty, I can't see your config because your link return void. 

Howerer, I post an update [v2.0.1](https://www.spigotmc.org/resources/ultimatets-link-minecraft-teamspeak-rank-easily-work-with-all-perms-plugins-mysql-opensource.39076/download?version=160784), try in this version ;)

**Comment by Harveh** [comment]
Sadly, it's still not working. Check my config to make sure it's right please. If you need any more info or the error message, then let me know!
Config: [https://prnt.sc/fabbfw](url)

p.s. sorry for the trouble with this :P I'm just really interested in getting this. :)

**Comment by DiscowZombie** [comment]
Hi,

all your config is great but the bot can't connect to your TeamSpeak because of because of your hosting proviser do not accept telnet connexion. When I try to login with Putty (same method as the bot) with the correct identifiants, I get this error: https://prnt.sc/fabrgc.

You need to contact your hosting proviser (of your TeamSpeak) and ask if they have change telnet connexion port for TeamSpeak. (knowing that the default port is 10011). Explain to your hosting proviser that your try to login to your TeamSpeak with serveradminquery login in putty using telnet method (port 10011) but the connexion return an error.

When you get an answer, post it here ;)


If you hosting providers can't help you, you need to purchase a personal machine (like VPS) and install TeamSpeak manually and it work ! :)

I'm sorry I can not help you anymore for the moment.

**Comment by Harveh** [comment]
Hey this is what they said.

"Unfortunately we don't have any telent/ssh login for our services. You can create a query login and use something called YATQA however."

Would this work or no?

**Comment by DiscowZombie** [comment]
Hi,

I'm sorry to disappointed you but no, they do not work. Yatqa is only a graphical interface for TeamSpeak query but the bot need a valid telent connection to acces your TeamSpeak.

If you want to use UltimateTs there are several solution:
- Change your hoster to get a TeamSpeak hosted on a machine who accept telnet/ssh connections.
- Purchase a VPS (or a dedicated server) and install TeamSpeak on it (you can found VPS very low cost). Verify that your hoster give you ssh access when purchasing.
- {Not the best way / Required ssh access} Host Minecraft servers who use UltimateTs and TeamSpeak on the same machine (with the same IP)


If you had other questions, I Say tuned !
